//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websitecoffeechoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int maGioHang { get; set; }
        public Nullable<long> maSanPham { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<int> maNguoiDung { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
